// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXzxVRxu1xO2m81CMqWJBulYwBkR-CC9Y',
    appId: '1:274562401957:web:22234e31d5a1a949c4ef4c',
    messagingSenderId: '274562401957',
    projectId: 'salonbeautyvibes-c32da',
    authDomain: 'salonbeautyvibes-c32da.firebaseapp.com',
    storageBucket: 'salonbeautyvibes-c32da.firebasestorage.app',
    measurementId: 'G-JSDLMGJVC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0flvNp_gqzPCFKf_5gr-3FzPMORs_mA',
    appId: '1:274562401957:android:2f28439d50ebf263c4ef4c',
    messagingSenderId: '274562401957',
    projectId: 'salonbeautyvibes-c32da',
    storageBucket: 'salonbeautyvibes-c32da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAVD5AADqkTIJ3BLjfHWY-PsbJtbKYV1o',
    appId: '1:274562401957:ios:74229f081c819ad3c4ef4c',
    messagingSenderId: '274562401957',
    projectId: 'salonbeautyvibes-c32da',
    storageBucket: 'salonbeautyvibes-c32da.firebasestorage.app',
    iosBundleId: 'com.example.salonbeautyvibes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAVD5AADqkTIJ3BLjfHWY-PsbJtbKYV1o',
    appId: '1:274562401957:ios:74229f081c819ad3c4ef4c',
    messagingSenderId: '274562401957',
    projectId: 'salonbeautyvibes-c32da',
    storageBucket: 'salonbeautyvibes-c32da.firebasestorage.app',
    iosBundleId: 'com.example.salonbeautyvibes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXzxVRxu1xO2m81CMqWJBulYwBkR-CC9Y',
    appId: '1:274562401957:web:94726fd3789b0bc5c4ef4c',
    messagingSenderId: '274562401957',
    projectId: 'salonbeautyvibes-c32da',
    authDomain: 'salonbeautyvibes-c32da.firebaseapp.com',
    storageBucket: 'salonbeautyvibes-c32da.firebasestorage.app',
    measurementId: 'G-M1Y1JKD1SQ',
  );

}